name: mypy

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip!=22.1.*
        python -m pip install --upgrade mypy
        python -m pip install ./yaqd_attune
    - name: Run mypy yaqd
      run: |
        cd yaqd-attune
        mypy yaqd_attune
    - name: Run mypy yaqg
      run: |
        cd yaqg-attune
        mypy yaqg_attune
